---
title: "Pilot PFAS Metabolic Cage Study"
subtitle: "7 days at 10mg/kg PFOA and PFOS"
author: "Jonathan Nelson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: 
      collapsed: false
      smooth_scroll: false
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=T, error=FALSE, message=FALSE, warning=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("Seurat")) {install.packages("Seurat"); require("Seurat")}
if (!require("SeuratDisk")) {install.packages("SeuratDisk"); require("SeuratDisk")}
if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!requireNamespace('BiocManager', quietly = TRUE)) {install.packages('BiocManager'); require("BiocManager")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("paletteer")) {install.packages("paletteer"); require("paletteer")} # color palette
if (!require("grDevices")) {install.packages("grDevices"); require("grDevices")} # for grDevices palette
if (!require("tidyverse")) {install.packages("tidyverse"); require("tidyverse")} # for data frame transformation
if (!require("tibble")) {install.packages("tibble"); require("tibble")} # for table transformation
if (!require("openxlsx")) {install.packages("openxlsx"); require("openxlsx")} # for table transformation
```

# Load Data

## Body Weight

```{r data3, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

df.BW <- read.xlsx(here("PFAS_Rdata.xlsx"))

df.meta <- read.xlsx(here("PFAS sample meta.xlsx"))

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

tidy_df <- df.BW %>%
  pivot_longer(
    cols = -X1,
    names_to = "ID",             # Name of the new column for IDs
    values_to = "Measurement"    # Name for the new column containing values
  ) 


df.meta$ID <- as.character(df.meta$ID)

tidy_df2 <- tidy_df %>% left_join(df.meta, by = c("ID" = "ID")) %>%
                        rename(Timepoint = X1)

tidy_df2$Timepoint <- factor(tidy_df2$Timepoint, levels = c("D-2", "D-1", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7"))
tidy_df2$Drug <- factor(tidy_df2$Drug, levels = c("Vehicle", "PFAS"))


tidy_df3 <- tidy_df2 %>%
  group_by(ID, Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
) 

tidy_df4 <- tidy_df2 %>%
  group_by(Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
)


tidy_df5 <- tidy_df4 %>%
  group_by(Drug) %>%
  mutate(NormalizedMean = Mean / first(Mean)) %>%
  mutate(NormalizedSD = SD / first(Mean))

tidy_df5$NormDown <- tidy_df5$NormalizedMean - tidy_df5$NormalizedSD
tidy_df5$NormUp <- tidy_df5$NormalizedMean + tidy_df5$NormalizedSD

tidy_df5$Timepoint <- factor(tidy_df5$Timepoint, levels = c("D-2", "D-1", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7"))
tidy_df5$Drug <- factor(tidy_df5$Drug, levels = c("Vehicle", "PFAS"))

# Example plot
ggplot(data = tidy_df5, aes(x = Timepoint, ymin = NormDown, ymax = NormUp, y = NormalizedMean, color = Drug, group = Drug, fill = Drug)) + 
  # Adding a gray backfill from D1 to D7
  geom_rect(aes(xmin = "D1" , xmax = "D7", ymin = -Inf, ymax = Inf), fill = "lightgray", alpha = 0.1, color = NA) +
  geom_line(size = 1.5) +  # Thicker line for better visibility
  geom_ribbon(aes(ymin = NormDown, ymax = NormUp), alpha = 0.5, color = NA) +  # Ensure ymin and ymax are specified
  annotate("text", x = "D1", y = .88, label = "PFAS", hjust = 0, vjust = 1, size = 10, color = "black") +  # Adding the text
  theme_classic() +
  labs(x = "Timepoint", y = "Normalized Mean", title = "Mouse Body Weight Over Study") +
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )





tidy_df6 <- tidy_df2 %>%
  group_by(Drug) %>%
  mutate(Normalized = Measurement / first(Measurement)) %>%
  filter(Timepoint == "D7")

tidy_df6$Drug <- factor(tidy_df6$Drug, levels = c("Vehicle", "PFAS"))


ggplot(data = tidy_df6, aes(x = Drug, y = Normalized, color = Drug)) + 
  geom_point(size = 3) +
  theme_classic() +
  labs(x = "Drug", y = "Normalized Measurement", title = "Body Weight at D7 by Drug Normalized to D-2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotate x-axis labels for better visibility
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12, angle = 0, hjust = .5),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )


```

## Food

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

df.BW <- read.xlsx(here("PFAS_Rdata_FoodWeight.xlsx"))

df.meta <- read.xlsx(here("PFAS sample meta.xlsx"))

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

tidy_df <- df.BW %>%
  pivot_longer(
    cols = -X1,
    names_to = "ID",             # Name of the new column for IDs
    values_to = "Measurement"    # Name for the new column containing values
  ) 


df.meta$ID <- as.character(df.meta$ID)

tidy_df2 <- tidy_df %>% left_join(df.meta, by = c("ID" = "ID")) %>%
                        rename(Timepoint = X1)

tidy_df2$Timepoint <- factor(tidy_df2$Timepoint, levels = c("D-1", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7"))
tidy_df2$Drug <- factor(tidy_df2$Drug, levels = c("Vehicle", "PFAS"))


tidy_df3 <- tidy_df2 %>%
  group_by(ID, Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
) 

tidy_df4 <- tidy_df2 %>%
  group_by(Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
)


tidy_df5 <- tidy_df4 %>%
  group_by(Drug) %>%
  mutate(NormalizedMean = Mean / first(Mean)) %>%
  mutate(NormalizedSD = SD / first(Mean))

tidy_df5$NormDown <- tidy_df5$NormalizedMean - tidy_df5$NormalizedSD
tidy_df5$NormUp <- tidy_df5$NormalizedMean + tidy_df5$NormalizedSD

# Example plot
ggplot(data = tidy_df5, aes(x = Timepoint, ymin = NormDown, ymax = NormUp, y = NormalizedMean, color = Drug, group = Drug, fill = Drug)) + 
  # Adding a gray backfill from D1 to D7
  geom_rect(aes(xmin = "D1" , xmax = "D7", ymin = -Inf, ymax = Inf), fill = "lightgray", alpha = 0.1, color = NA) +
  geom_line(size = 1.5) +  # Thicker line for better visibility
  geom_ribbon(aes(ymin = NormDown, ymax = NormUp), alpha = 0.5, color = NA) +  # Ensure ymin and ymax are specified
  annotate("text", x = "D1", y = .75, label = "PFAS", hjust = 0, vjust = 1, size = 10, color = "black") +  # Adding the text
  theme_classic() +
  labs(x = "Timepoint", y = "Normalized Mean", title = "Food Consumption Over Study") +
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )

tidy_df6 <- tidy_df2 %>%
  group_by(Drug) %>%
  mutate(Normalized = Measurement / first(Measurement)) %>%
  filter(Timepoint == "D7")

tidy_df6$Drug <- factor(tidy_df6$Drug, levels = c("Vehicle", "PFAS"))


ggplot(data = tidy_df6, aes(x = Drug, y = Normalized, color = Drug)) + 
  geom_point(size = 3) +
  theme_classic() +
  labs(x = "Drug", y = "Normalized Measurement", title = "Food Consumption at D7 by Drug Normalized to D-1") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotate x-axis labels for better visibility
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12, angle = 0, hjust = .5),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )


```



## Urine Volume

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

df.BW <- read.xlsx(here("PFAS_Rdata_UrineVolume.xlsx"))

df.meta <- read.xlsx(here("PFAS sample meta.xlsx"))

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

tidy_df <- df.BW %>%
  pivot_longer(
    cols = -X1,
    names_to = "ID",             # Name of the new column for IDs
    values_to = "Measurement"    # Name for the new column containing values
  ) 

tidy_df$Measurement <- tidy_df$Measurement - 2.9

df.meta$ID <- as.character(df.meta$ID)

tidy_df2 <- tidy_df %>% left_join(df.meta, by = c("ID" = "ID")) %>%
                        rename(Timepoint = X1)

tidy_df2$Timepoint <- factor(tidy_df2$Timepoint, levels = c("D-1", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7"))
tidy_df2$Drug <- factor(tidy_df2$Drug, levels = c("Vehicle", "PFAS"))


tidy_df3 <- tidy_df2 %>%
  group_by(ID, Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
) 

tidy_df4 <- tidy_df2 %>%
  group_by(Timepoint, Drug) %>%
  summarize(
    Mean = mean(Measurement, na.rm = TRUE),
    SD = sd(Measurement, na.rm = TRUE)/sqrt(5)
)


tidy_df5 <- tidy_df4 %>%
  group_by(Drug) %>%
  mutate(NormalizedMean = Mean / first(Mean)) %>%
  mutate(NormalizedSD = SD / first(Mean))

tidy_df5$NormDown <- tidy_df5$NormalizedMean - tidy_df5$NormalizedSD
tidy_df5$NormUp <- tidy_df5$NormalizedMean + tidy_df5$NormalizedSD

# Example plot
ggplot(data = tidy_df5, aes(x = Timepoint, ymin = NormDown, ymax = NormUp, y = NormalizedMean, color = Drug, group = Drug, fill = Drug)) + 
  # Adding a gray backfill from D1 to D7
  geom_rect(aes(xmin = "D1" , xmax = "D7", ymin = -Inf, ymax = Inf), fill = "lightgray", alpha = 0.1, color = NA) +
  geom_line(size = 1.5) +  # Thicker line for better visibility
  geom_ribbon(aes(ymin = NormDown, ymax = NormUp), alpha = 0.5, color = NA) +  # Ensure ymin and ymax are specified
  annotate("text", x = "D1", y = .65, label = "PFAS", hjust = 0, vjust = 1, size = 10, color = "black") +  # Adding the text
  theme_classic() +
  labs(x = "Timepoint", y = "Normalized Mean", title = "Urine Volume Over Study") +
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )

tidy_df6 <- tidy_df2 %>%
  group_by(Drug) %>%
  mutate(Normalized = Measurement / first(Measurement)) %>%
  filter(Timepoint == "D7")

tidy_df6$Drug <- factor(tidy_df6$Drug, levels = c("Vehicle", "PFAS"))


ggplot(data = tidy_df6, aes(x = Drug, y = Normalized, color = Drug)) + 
  geom_point(size = 3) +
  theme_classic() +
  labs(x = "Drug", y = "Normalized Measurement", title = "Urine Volume at D7 by Drug Normalized to D-1") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotate x-axis labels for better visibility
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12, angle = 0, hjust = .5),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )


```

## Tissue Measurements

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

df.BW <- read.xlsx(here("PFAS_Rdata_tissue.xlsx"))

df.meta <- read.xlsx(here("PFAS sample meta.xlsx"))

```

```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

df.meta$ID <- as.character(df.meta$ID)
df.BW$ID <- as.character(df.BW$ID)

tidy_df2 <- df.BW %>% left_join(df.meta, by = c("ID" = "ID")) 

tidy_df2$Drug <- factor(tidy_df2$Drug, levels = c("Vehicle", "PFAS"))

ggplot(data = tidy_df2, aes(x = Drug, y = KW_BW, color = Drug)) + 
  geom_point(size = 3) +
  theme_classic() +
  labs(x = "Drug", y = "KW/BW (mg/g)", title = "Kidney Weight to Body Weight (D7) Ratio") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotate x-axis labels for better visibility
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12, angle = 0, hjust = .5),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )

ggplot(data = tidy_df2, aes(x = Drug, y = HW_BW, color = Drug)) + 
  geom_point(size = 3) +
  theme_classic() +
  labs(x = "Drug", y = "HW/BW (mg/g)", title = "Heart Weight to Body Weight (D7) Ratio") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotate x-axis labels for better visibility
    theme(
    axis.title.x = element_text(size = 14),  # Increase x-axis title size
    axis.title.y = element_text(size = 14),  # Increase y-axis title size
    axis.text.x = element_text(size = 12, angle = 0, hjust = .5),    # Increase x-axis text size
    axis.text.y = element_text(size = 12),    # Increase y-axis text size
    plot.title = element_text(size = 16, hjust = 0.5)       # Increase plot title size
  )



```




```{r echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}
sessionInfo()
```
